version: 2.1
jobs:
  sonar:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar


  TestNet:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/tmp

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache: 
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run:
          name: Run Tests
          command: |
                    mvn verify -DRskNetwork=Testnet


      - store_artifacts:
          path: /home/circleci/tmp/target/jmeter/reports
          destination: ~/tmp/Results
          
      - store_artifacts:
          path: target/jmeter/results
          destination: ~/tmp/Results
  MainNet:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/tmp

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache: 
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run:
          name: Run Tests
          command: |
                    mvn verify -DRskNetwork=Mainnet


      - store_artifacts:
          path: /home/circleci/tmp/target/jmeter/reports
          destination: ~/tmp/Results
          
      - store_artifacts:
          path: target/jmeter/results
          destination: ~/tmp/Results

workflows:
    commit:
        jobs:
            - TestNet
            - MainNet
            - Sonar
    MainNet-morning:
        triggers:
            - schedule:
                cron: "00 09 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - MainNet
    MainNet-afternoon:
        triggers:
            - schedule:
                cron: "00 17 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - MainNet
    MainNet-night:
        triggers:
            - schedule:
                cron: "00 01 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - MainNet
    TestNet-morning:
        triggers:
            - schedule:
                cron: "02 09 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - TestNet  
    TestNet-afternoon:
        triggers:
            - schedule:
                cron: "02 17 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - TestNet
    TestNet-night:
        triggers:
            - schedule:
                cron: "02 01 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - TestNet
